//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z_City.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z_City.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 60
        ///A 1
        ///B 2
        ///C 3
        ///D 2
        ///E 1
        ///F 2
        ///G 3
        ///H 4
        ///I 3
        ///J 2
        ///K 3
        ///L 4
        ///M 5
        ///N 4
        ///O 3
        ///P 2
        ///Q 3
        ///R 4
        ///S 3
        ///T 2
        ///U 1
        ///V 2
        ///W 3
        ///X 2
        ///Y 1
        ///A C 13 0
        ///A B 10 1
        ///C B 21 1
        ///C D 11 1
        ///D E 12 1
        ///A G 19 0
        ///B H 17 0
        ///D H 15 0
        ///E I 23 0
        ///E J 10 0
        ///E O 16 0
        ///A F 5 0
        ///F G 18 1
        ///G B 24 1
        ///G H 10 0
        ///H C 18 1
        ///H I 27 1
        ///D I 15 1
        ///I J 25 1
        ///F L 14 1
        ///F K 25 0
        ///K L 13 1
        ///G M 13 1
        ///G L 9 0
        ///L M 14 0
        ///I M 13 0
        ///H M 14 1
        ///M N 5 1
        ///N J 22 1
        ///I N 21 0
        ///N O 13 0
        ///J O 15 0
        ///P L 13 1
        ///K P 22 0
        ///P Q 17 0
        ///M Q 18 1
        ///L Q 8 1
        ///Q R 15 0
        ///M S  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
    }
}
